export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
